// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: fibServer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FibRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *FibRequest) Reset() {
	*x = FibRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fibServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibRequest) ProtoMessage() {}

func (x *FibRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fibServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibRequest.ProtoReflect.Descriptor instead.
func (*FibRequest) Descriptor() ([]byte, []int) {
	return file_fibServer_proto_rawDescGZIP(), []int{0}
}

func (x *FibRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type FibReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *FibReply) Reset() {
	*x = FibReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fibServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibReply) ProtoMessage() {}

func (x *FibReply) ProtoReflect() protoreflect.Message {
	mi := &file_fibServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibReply.ProtoReflect.Descriptor instead.
func (*FibReply) Descriptor() ([]byte, []int) {
	return file_fibServer_proto_rawDescGZIP(), []int{1}
}

func (x *FibReply) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_fibServer_proto protoreflect.FileDescriptor

var file_fibServer_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x46, 0x69, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x42, 0x22, 0x1e,
	0x0a, 0x0a, 0x46, 0x69, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x1c,
	0x0a, 0x08, 0x46, 0x69, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x32, 0x4d, 0x0a, 0x09,
	0x46, 0x69, 0x62, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x62, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x46, 0x69, 0x62, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x42, 0x2e, 0x46, 0x69, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x46, 0x69, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x42,
	0x2e, 0x46, 0x69, 0x62, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x66,
	0x69, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fibServer_proto_rawDescOnce sync.Once
	file_fibServer_proto_rawDescData = file_fibServer_proto_rawDesc
)

func file_fibServer_proto_rawDescGZIP() []byte {
	file_fibServer_proto_rawDescOnce.Do(func() {
		file_fibServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_fibServer_proto_rawDescData)
	})
	return file_fibServer_proto_rawDescData
}

var file_fibServer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fibServer_proto_goTypes = []interface{}{
	(*FibRequest)(nil), // 0: FibServerPB.FibRequest
	(*FibReply)(nil),   // 1: FibServerPB.FibReply
}
var file_fibServer_proto_depIdxs = []int32{
	0, // 0: FibServerPB.FibWorker.GetFibNumber:input_type -> FibServerPB.FibRequest
	1, // 1: FibServerPB.FibWorker.GetFibNumber:output_type -> FibServerPB.FibReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fibServer_proto_init() }
func file_fibServer_proto_init() {
	if File_fibServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fibServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fibServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fibServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fibServer_proto_goTypes,
		DependencyIndexes: file_fibServer_proto_depIdxs,
		MessageInfos:      file_fibServer_proto_msgTypes,
	}.Build()
	File_fibServer_proto = out.File
	file_fibServer_proto_rawDesc = nil
	file_fibServer_proto_goTypes = nil
	file_fibServer_proto_depIdxs = nil
}
